sagasurvey/saga

SAGA/hosts/host_catalog.py, SAGA/objects/object_catalog.py, SAGA/utils/functions.py
This makes 3 "usability" adjustments that I've found useful for messing around with this code (mostly informed by my past codes on target selection):
* switch to using quantities in a few places (where it doesn't have any significant performance implications)
* makes the `Database` use local copies of google sheets *if* the web is inaccessible (I was on a 6hr flight...)
* Adds a SkyCoord object to the tables to make things like matching easier
=> Usability enhanements

SAGA/targets/gmm.py, SAGA/version.py
also increases version to 0.5.6
=> bug fix and small improvement for GMM code

SAGA/database/saga_database.py, SAGA/targets/assign_targeting_score.py, SAGA/targets/target_selection.py, SAGA/version.py
[See an example usage here](https://github.com/sagasurvey/examples/blob/master/notebooks/target%20selection%20example.ipynb)
=> Update target selection

SAGA/targets/target_selection.py, SAGA/version.py
Just what it says (see slack for a bit more, @yymao)
=> add code to add dashes required in mmt file header

SAGA/objects/build.py, SAGA/targets/assign_targeting_score.py, SAGA/targets/target_selection.py, SAGA/version.py
This PR includes some minor fixes, in particular to make MMT target catalogs more reproducible and also fix an issue in base catalog building.
=> Minor updates

SAGA/database/external.py, SAGA/database/saga_database.py, SAGA/version.py
This PR adds functionality to obtain DES and DECaLS catalogs. (Note that for DECaLS, the code needs to be run on NERSC or a machine where DECaLS sweep data exist).
=> Des and decals catalogs

SAGA/objects/build.py, SAGA/objects/build2.py, SAGA/targets/gmm.py, SAGA/utils/functions.py, SAGA/version.py
Use kcorrect to calculate stellar (using code from @marlageha)
=> Add stellar mass

SAGA/objects/build.py, SAGA/objects/build2.py, SAGA/utils/functions.py, SAGA/version.py
bug fix for stellar mass calculation (previous version conflicts with masked astropy table)
=> Stellar mass bug fix

SAGA/database/spectra.py, SAGA/objects/build2.py, SAGA/objects/object_catalog.py, SAGA/targets/target_selection.py, SAGA/version.py
This PR adds heliocentric correction to MMT and AAT specs.
=> add heliocentric correction

SAGA/hosts/host_catalog.py, SAGA/objects/object_catalog.py, SAGA/targets/target_selection.py, SAGA/version.py, test.py
thanks @marlageha for discovering this bug
=> A quick bug fix

SAGA/objects/build.py, SAGA/objects/build2.py, SAGA/version.py
This PR adds `replace_poor_sdss_sky_subtraction` (from @marlageha) and changes high-z removal radius multiple.
=> Improving build2

SAGA/targets/target_selection.py, SAGA/version.py
@eteq I'll be working on this branch to fix some of the issues you mentioned.
=> potentially fixes the star fiber issue

SAGA/targets/target_selection.py
This will have a running set of updates based on changes I made to make the AAT run go more smoothly.
=> AAT Night 1 tweaks

SAGA/objects/object_catalog.py
Minor, but very useful for keeping paths straight
=> add printing of base catalog path

SAGA/database/saga_database.py, SAGA/database/spectra.py, SAGA/version.py
This PR adds OzDES specs and some bug fixes to `SPEC_Z_ERR`.
=> Read OzDES specs

SAGA/database/core.py, SAGA/database/spectra.py, SAGA/objects/object_catalog.py, SAGA/targets/target_selection.py, SAGA/version.py
Use `add_specs_only_before_time` option when calling `build_and_write_to_database`
=> Allow building base catalogs with only specs taken before certain time

SAGA/objects/build2.py, SAGA/objects/object_catalog.py, SAGA/version.py
This PR implements a more robust matching scheme when we match the spectra back to photometric objects.
=> Update the method that matches specs to photo objs

SAGA/database/saga_database.py, SAGA/objects/build.py, SAGA/objects/build2.py, SAGA/objects/object_catalog.py, SAGA/version.py
This PR adds DECaLS remove/recover list and also uses a better pipeline for manually remove/recover objects.
Version bumped to 0.6.28
=> add DECaLS remove/recover list

SAGA/database/saga_database.py, SAGA/database/spectra.py, SAGA/version.py
Added code to read 2dflens catalog.  This is a .dat ascii file, so not certain this will run properly.
=> try to add 2dflens

SAGA/objects/object_catalog.py, SAGA/targets/target_selection.py, SAGA/version.py
As title. Version bumped to 0.6.30
=> make `prepare_mmt_catalog` work with merged base catalogs

SAGA/objects/build2.py, SAGA/version.py
The original calculation results in nan or infinity in cases if shouldn't. This new code fixes that.
=> fix radius errors in for DECaLS objects

SAGA/database/external.py, SAGA/objects/build2.py, SAGA/version.py
Working with @marlageha, we've come up a new set of remove flags to remove junks in DECaLS more aggressively.  
This PR fixes #56.
=> Update DECaLS remove flags

SAGA/spectra/read_external.py, SAGA/version.py
- set `ZQUALITY` to 2 for low-z (z < 0.05) and `ZQUALITY == 3` objects in 2dF and 2dFLens
- slightly refactor `read_external.py` to make code more consistent
=> Better external specs

SAGA/database/saga_database.py, SAGA/objects/cuts.py, SAGA/spectra/read_external.py, SAGA/version.py
I added wigglez in read_external and saga_database.   I am missing the actual read statement.  Where are these read in?
=> Mgeha edits

SAGA/objects/build.py, SAGA/objects/cuts.py, SAGA/utils/display.py
This PR adds a few useful but minor updates to the code base
=> misc useful updates

SAGA/objects/cuts.py
Use `QueryMaker` to make complicated queries more readable.
=> use QueryMaker

SAGA/database/saga_database.py, SAGA/hosts/cuts.py, SAGA/objects/build2.py, SAGA/objects/build3.py, SAGA/objects/cuts.py, SAGA/objects/object_catalog.py, SAGA/utils/functions.py, SAGA/version.py
Three major changes
- Translate BASS r mag to DECaLS
- Fix effective radius (were using semi-major axis)
- Add new paper 3 targeting cuts
=> Version 0.41

SAGA/objects/build3.py, SAGA/version.py
Quenched definition proposed by @marlageha
=> update quenched definition

SAGA/objects/build3.py, SAGA/objects/calc_sfr.py, SAGA/version.py
`nuv_mag` and `fuv_mag` in the base catalog should include external extinction correction like other magnitudes in the base catalog.
=> Implement UV external extinction correction

SAGA/database/saga_database.py, SAGA/objects/build2.py, SAGA/objects/cuts.py, SAGA/spectra/common.py, SAGA/spectra/read_external.py, SAGA/spectra/spectra_data_object.py, SAGA/version.py
New code is currently being tested.  Please wait to merge.
=> Incorporate more external specs
